---
title: "Sample Code: R"
editor_options: 
  chunk_output_type: console
---


# Elements of R

```{r load}

library(tidyverse)
library(socviz)

```


```{r objects, echo=TRUE}
c(1, 2, 3, 1, 3, 5, 25)
```


```{r, echo=TRUE}
my_numbers <- c(1, 2, 3, 1, 3, 5, 25)

your_numbers <- c(5, 31, 71, 1, 3, 21, 6)
```


```{r, echo=TRUE}
my_numbers
```


```{r mean-example-2, echo=TRUE, eval=FALSE}
mean()

# Error in mean.default() : argument "x" is missing, with no default
```

```{r mean-example-3, echo=TRUE}
mean(x = my_numbers)
mean(x = your_numbers)
```


```{r functions-2, echo=TRUE}
my_summary <- summary(my_numbers)
```


```{r output}

table(my_numbers)

sd(my_numbers)

my_numbers * 5

my_numbers + 1

my_numbers + my_numbers

```


```{r getclass}
class(my_numbers)
class(my_summary)
class(summary)
```


```{r titanic1}
titanic
class(titanic)
```


```{r titanic3}
titanic_tb <- as_tibble(titanic)
titanic_tb
```


```{r str}

str(my_numbers)
str(my_summary)

```

# The CQ data

```{r setup2, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(lubridate)
library(socviz)

```

```{r local-functions}

## Calculate age in years, months, or days
calc_age <- function(birth_date, ref_date = Sys.Date(), unit = "year") {

    require(lubridate)

    period <- as.period(interval(birth_date, ref_date),
                        unit = unit)

    switch(unit,
           year = year(period),
           month = month(period),
           day = day(period),
           stop = "Unknown time unit. Choose year, month, or day.")

}

```

## Load it

```{r load2}

filenames <- dir(path = "data/clean",
                 pattern = "*.csv",
                 full.names = TRUE)

filenames

specs <- spec_csv(filenames[1])

specs

data <- filenames %>%
    map_dfr(read_csv, .id = "congress", col_types = specs)

data <- clean_names(data)

data

```

